### ISSUE TITLE
RGraph overlapping

### ISSUE THREAD

**Issue by wallace1981** [philogb/jit#10]
Hi!
I've been noticed by a little problem, seems like overlapping.
Please take a look: http://www.easy-upload.net/fichier.php?fichier=200983120533.

**Comment by philogb** [comment]
Hi, 

This doesn't seem to be a problem of the library, since all other labels are well displayed in the graph. Are you sure you're providing the nodes with unique ids?

I'll need more information to know what's going on, but a priori it doesn't seem a problem of the library.

Perhaps you'd like to discuss this in the google group first?

**Comment by wallace1981** [comment]
Here comes the JSON http://www.easy-upload.net/fichier.php?fichier=2009831212343 (save picture, this is usual .js script).
Thanks, i will also post my issue at google group.

**Comment by philogb** [comment]
As I explained here:

http://groups.google.com/group/javascript-information-visualization-toolkit/browse_thread/thread/b5b83dc26b85ba93

This has more to do with the data being a non-connected graph than with the library itself.
